# permissions for end users to edit clustertemplatesetups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustertemplatesetup-editor-role
rules:
- apiGroups:
  - clustertemplate.rawagner.com
  resources:
  - clustertemplatesetups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustertemplate.rawagner.com
  resources:
  - clustertemplatesetups/status
  verbs:
  - get
