# permissions for end users to view clustertemplateinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustertemplateinstance-viewer-role
rules:
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplateinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplateinstances/status
  verbs:
  - get
