# permissions for end users to view clustertemplatequota.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustertemplatequota-viewer-role
rules:
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplatequotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplatequotas/status
  verbs:
  - get
