# permissions for end users to edit clustertemplatequota.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustertemplatequota-editor-role
rules:
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplatequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplatequotas/status
  verbs:
  - get
