# permissions for end users to edit clustertemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustertemplate-editor-role
rules:
- apiGroups:
  - clustertemplate.rawagner.com
  resources:
  - clustertemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustertemplate.rawagner.com
  resources:
  - clustertemplates/status
  verbs:
  - get
