# permissions for end users to view clustertemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustertemplate-viewer-role
rules:
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplates/status
  verbs:
  - get
