# permissions for end users to edit clustertemplateinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustertemplateinstance-editor-role
rules:
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplateinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplateinstances/status
  verbs:
  - get
