# permissions for end users to view clustertemplatequota.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustertemplatequota-viewer-role
rules:
- apiGroups:
  - clustertemplate.rawagner.com
  resources:
  - clustertemplatequota
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clustertemplate.rawagner.com
  resources:
  - clustertemplatequota/status
  verbs:
  - get
