---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - clustertemplate.rawagner.com
  resources:
  - clustertemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustertemplate.rawagner.com
  resources:
  - clustertemplates/finalizers
  verbs:
  - update
- apiGroups:
  - clustertemplate.rawagner.com
  resources:
  - clustertemplates/status
  verbs:
  - get
  - patch
  - update
